/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.ctrdn.stuba.pks.netanalyser.am.frameinfo;

import java.util.List;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.ctrdn.stuba.pks.netanalyser.common.DataTypeHelpers;
import net.ctrdn.stuba.pks.netanalyser.common.NonEditableColorableDefaultTableModel;
import net.ctrdn.stuba.pks.netanalyser.exception.AnalyserModuleException;
import net.ctrdn.stuba.pks.netanalyser.exception.DataTypeException;
import net.ctrdn.stuba.pks.netanalyser.parser.EthernetFrame;
import org.krakenapps.pcap.util.Buffer;

/**
 *
 * @author castor
 */
public class FrameInfoPanel extends javax.swing.JPanel {

    private List<EthernetFrame> frameList;

    public FrameInfoPanel(FrameInfoAnalyserModule analyserModule) {
        initComponents();
        this.jTableFrameTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int tableRowId = FrameInfoPanel.this.jTableFrameTable.getSelectedRow();
                if (tableRowId >= 0) {
                    int frameId = (Integer) FrameInfoPanel.this.jTableFrameTable.getModel().getValueAt(tableRowId, 0);
                    if (FrameInfoPanel.this.frameList != null) {
                        Buffer frameBuffer = FrameInfoPanel.this.frameList.get(frameId).getDataBuffer();
                        int posBackup = frameBuffer.position();
                        frameBuffer.rewind();
                        FrameInfoPanel.this.jTextPaneFrameData.setText(DataTypeHelpers.getFrameDataFormatted(frameBuffer, 32));
                        FrameInfoPanel.this.jTextPaneFrameData.setCaretPosition(0);
                        frameBuffer.rewind();
                        frameBuffer.skip(posBackup);
                    }
                }
            }
        });
    }

    protected void update(List<EthernetFrame> frameList, int filteredFrameCount, int totalFrameCount) throws AnalyserModuleException {
        try {
            this.frameList = frameList;
            DefaultTableModel tableModel = new NonEditableColorableDefaultTableModel(new Object[]{"#", "Capture Time Offset", "Original Length", "Wire Length", "Type", "Source MAC", "Destination MAC"}, 0);
            for (EthernetFrame frame : frameList) {
                tableModel.addRow(new Object[]{frame.getCaptureId(), frame.getCaptureTimeOffset() + " ms", frame.getCaptureOriginalLength(), frame.getCaptureWireLength(), DataTypeHelpers.getFrameTypeString(frame.getEthernetFrameType()), frame.getEthernetSourceMacAddressString(), frame.getEthernetDestinationMacAddressString()});
            }
            this.jTableFrameTable.setModel(tableModel);
        } catch (DataTypeException ex) {
            AnalyserModuleException finalEx = new AnalyserModuleException("Failed to update analyser");
            finalEx.addSuppressed(ex);
            throw finalEx;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFrameTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneFrameData = new javax.swing.JTextPane();

        setName("Frame Info"); // NOI18N

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLastDividerLocation(100);

        jTableFrameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableFrameTable);

        jSplitPane1.setTopComponent(jScrollPane1);

        jTextPaneFrameData.setEditable(false);
        jTextPaneFrameData.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jScrollPane2.setViewportView(jTextPaneFrameData);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jSplitPane1.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableFrameTable;
    private javax.swing.JTextPane jTextPaneFrameData;
    // End of variables declaration//GEN-END:variables

    public JTable getTable() {
        return this.jTableFrameTable;
    }
}
